version: '2.1'

services:
  websocket:
    extends:
      file: websocket.yml
      service: websocket${ORO_PHP:-7.1}
    ports:
      - "8080"
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN
      - SYMFONY_ENV
      - SYMFONY_DEBUG

  websocket5.6:
    image: oroinc/websocket:5.6-xenial

  websocket7.0:
    image: oroinc/websocket:7.0-xenial

  websocket7.1:
    image: oroinc/websocket:7.1-xenial
