version: '2.1'

services:
  database:
    extends:
      file: mysql.yml
      service: mysql${MYSQL:-5.5}
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: oro_db
      MYSQL_USER: oro_db_user
      MYSQL_PASSWORD: oro_db_pass
    ports:
      - "3306"
    expose:
      - "3306"
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping && test ! -f /var/lib/mysql_data/db_lock"]
      interval: 30s
      timeout: 5s
      retries: 20

  mysql5.5:
    image: oroinc/mysql:${PATCH:-5.5}-${ORO_INSTALLED:-empty}

  mysql5.6:
    image: oroinc/mysql:${PATCH:-5.6}-${ORO_INSTALLED:-empty}

  mysql5.7:
    image: oroinc/mysql:${PATCH:-5.7}-${ORO_INSTALLED:-empty}

  mysql8.0:
    image: oroinc/mysql:${PATCH:-8.0}-${ORO_INSTALLED:-empty}
